version: '3.8'

services:
  # 1. Database (Different Port)
  mongodb-jenkins:
    image: mongo:latest
    container_name: autom8-db-jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-jenkins:/data/db
    networks:
      - autom8-network-jenkins

  # 2. Backend (Different Port, Volume for Code)
  backend-jenkins:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: autom8-backend-jenkins-img # Tag the built image explicitly
    container_name: autom8-backend-jenkins
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5001:5000"
    command: sh -c "npm install && npm start"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb-jenkins:27017/marketing_automation
    depends_on:
      - mongodb-jenkins
    networks:
      - autom8-network-jenkins

  # 3. Frontend (Different Port, Volume for Code)
  frontend-jenkins:
    image: node:20-alpine
    container_name: autom8-frontend-jenkins
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend-jenkins
    networks:
      - autom8-network-jenkins

volumes:
  mongo-data-jenkins:


networks:
  autom8-network-jenkins:
    driver: bridge
